import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/app/(auth)/components/Navbar";
import ReactQueryClientProvider from "@/provider/ReactQueryClientprovider";
import AuthGuard from "@/guard/AuthGuard";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <AuthGuard>
          <ReactQueryClientProvider>
            <Navbar />
            {children}
          </ReactQueryClientProvider>
        </AuthGuard>
      </body>
    </html>
  );
}
